name: Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: pip install requests

      - run: python repo_scanner.py
        env:
          GHP_TOKEN: ${{ secrets.GHP_TOKEN_CUSTOM }}

      - uses: actions/upload-artifact@v4
        with:
          name: repos
          path: repos.txt
