name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: repos

      - run: pip install requests

      - run: python sync_engine.py
        env:
          GHP_USERNAME: ${{ secrets.GHP_USERNAME }}
          GHP_TOKEN: ${{ secrets.GHP_TOKEN_CUSTOM }}
          GITLAB_URL: https://git.sysu.edu.cn
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
